configuration:  
  projectName: ADMA-Ping
server:  
  port: 8080
---
spring:
  profiles: environments
Global:
  ${ENVIRONMENT_PREFIX}-ADMAPing:
    serverType: Web
    properties:
      CNAMEPrefix: ${environment_prefix}-ADMAPing
    Tags:
      Key:
        - "careem:environment"
        - "careem:criticality"
        - "careem:tier"
        - "careem:team"
      Value:
        - "${ENVIRONMENT_PREFIX}"
        - "low"
        - "Web"
        - "${team_name}"
---
spring:
  profiles: versions
Global:
  ${ENVIRONMENT_PREFIX}-ADMAPing:
    properties:
      SourceBundle: 
        S3Key: admaping
---
spring:
  profiles: configurationTemplate
Global:
  ${ENVIRONMENT_PREFIX}-ADMAPing:
    properties:
      SolutionStackName: SS
      NumberOfOptionSettings: 22
      OptionSettings:
        OptionName:
          - InstanceType
          - AssociatePublicIpAddress
          - Subnets
          - ELBSubnets
          - EnvironmentType
          - EnvironmentVariables
          - SecurityGroups
          - Availability Zones
          - Target
          - CrossZone
          - Application Healthcheck URL
          - LoadBalancerHTTPSPort
          - SSHSourceRestriction
          - LoadBalancerType
          - LowerThreshold
          - UpperThreshold
          - EC2KeyName
          - IamInstanceProfile
          - VPCId
          - ServiceRole
          - Notification Endpoint
          - SSLCertificateId
        Namespace:
          - aws:autoscaling:launchconfiguration
          - aws:ec2:vpc
          - aws:ec2:vpc
          - aws:ec2:vpc
          - aws:elasticbeanstalk:environment
          - aws:cloudformation:template:parameter
          - aws:autoscaling:launchconfiguration
          - aws:autoscaling:asg
          - aws:elb:healthcheck
          - aws:elb:loadbalancer
          - aws:elasticbeanstalk:application
          - aws:elb:loadbalancer
          - aws:autoscaling:launchconfiguration
          - aws:elasticbeanstalk:environment
          - aws:autoscaling:trigger
          - aws:autoscaling:trigger
          - aws:autoscaling:launchconfiguration
          - aws:autoscaling:launchconfiguration
          - aws:ec2:vpc
          - aws:elasticbeanstalk:environment
          - aws:elasticbeanstalk:sns:topics
          - aws:elb:listener:443
        Value:
          - t2.medium
          - true
          - subnet-123
          - subnet-456
          - LoadBalanced
          - EnvVar
          - sg-789
          - Any
          - /hello
          - true
          - /hello
          - 123
          - 456
          - classic
          - 2000000
          - 6000000
          - key
          - aws-elasticbeanstalk-ec2-role
          - vpc-789
          - aws-elasticbeanstalk-service-role
          - help.com
          - certificate