configuration:
  projectName: master-service
server:  
  port: 8000
---
spring:
  profiles: Apps
applications:
  total: 16
  names:
    - ADMA-Ping
    - CaptainAssigner
    - CaptainDisputeService
    - Careem-Prod-BackEnd
    - Careem-Prod-FrontEnd
    - DispatchHandler
    - Edge Services
    - EventProcessor
    - Fawry
    - Locations
    - Microservices
    - Microservices-Docker
    - Promotions
    - Solutions
    - TripReport
    - Workers
---
spring: 
  profiles: Servers
servers:
  prod:
    total: 18
    names:
      - Prod-Authentication-Service
      - Prod-Core-Service-ADMA
      - Prod-Core-Service-App
      - Prod-Core-Service-OPS
      - Prod-Core-Service-Scripts
      - Prod-Docker-Captain-Expedition
      - Prod-Eta-Service
      - Prod-Trip-Report-Service
      - Prod-Worker-Captain-Ping-Director
      - Prod-Worker-Captain-Realtime-Pings
      - Prod-Worker-Colleague-Zendesk
      - Prod-Worker-Communication-DeadLetters
      - Prod-Quality-Control-Service
      - Prod-Consumer-Api-Gateway
      - Prod-Supply-Service
      - Prod-Captain-utility-edge-service
      - Prod-Captain-Api-Gateway
      - Prod-Solutions
