configuration:  
  projectName: Edge Services
server:  
  port: 8080
properties:
  status: 1
---
spring:
  profiles: environments
Staging:
  STG-ConsumerEdgeService:
    status: 0
    serverType: Web
    properties:
      VersionLabel: STGConsumerEdgeServiceVersion
      TemplateName: STGConsumerEdgeServiceTemplate
      CNAMEPrefix: STG-ConsumerEdgeService
---
spring:
  profiles: versions
Staging:
  STGConsumerEdgeServiceVersion:
    properties:
      Description: AWS ElasticBeanstalk Staging STG-ConsumerEdgeService Version
      SourceBundle: 
        S3Key: coreapp
---
spring:
  profiles: configurationTemplate
Staging:
  STGConsumerEdgeServiceTemplate:
    properties:
      Description: AWS ElasticBeanstalk STG-ConsumerEdgeService Configuration Template
      SolutionStackName: 64bit Amazon Linux 2016.03 v2.2.0 running Tomcat 8 Java 8
      NumberOfOptionSettings: 34
      OptionSettings:
        Value:
          - 2
          - Careem-Servers
          - aws-elasticbeanstalk-ec2-role
          - m3.medium
          - sg-c6d941a3,sg-16ad6271
          - 1
          - 80
          - CPUUtilization
          - 1
          - Percent
          - 85
          - XX|MaxPermSize=1024m,Xmx=3072m,JVM_#_Options=-Djdk.xml.entityExpansionLimit=0,Xms=512m
          - false
          - subnet-73e38805
          - subnet-73e38805
          - vpc-b032acd4
          - 1
          - arn|aws|acm|eu-west-1|848569320300|certificate/7f7a5da9-07cc-4d77-94e8-93503482ba31
          - true
          - zeeshan.habib@careem.com
          - 50
          - io1
          - 200
          - 2
          - 2
          - 1
          - 45_#_*_#_*_#_*_#_*
          - 2015-06-16T11|00|00Z
          - false
          - public
          - Fixed
          - true
          - Dev
          - ENVVAR
        Namespace: 
          - aws|autoscaling|asg
          - aws|autoscaling|launchconfiguration
          - aws|autoscaling|launchconfiguration
          - aws|autoscaling|launchconfiguration
          - aws|autoscaling|launchconfiguration
          - aws|autoscaling|trigger
          - aws|autoscaling|trigger
          - aws|autoscaling|trigger
          - aws|autoscaling|trigger
          - aws|autoscaling|trigger
          - aws|autoscaling|trigger
          - aws|cloudformation|template|parameter
          - aws|ec2|vpc
          - aws|ec2|vpc
          - aws|ec2|vpc
          - aws|ec2|vpc
          - aws|elasticbeanstalk|command
          - aws|elb|loadbalancer
          - aws|elb|policies
          - aws|elasticbeanstalk|sns|topics
          - aws|autoscaling|launchconfiguration
          - aws|autoscaling|launchconfiguration
          - aws|autoscaling|launchconfiguration
          - aws|autoscaling|scheduledaction
          - aws|autoscaling|scheduledaction
          - aws|autoscaling|scheduledaction
          - aws|autoscaling|scheduledaction
          - aws|autoscaling|scheduledaction
          - aws|autoscaling|scheduledaction
          - aws|ec2|vpc
          - aws|elasticbeanstalk|command
          - aws|elb|loadbalancer
          - aws|elasticbeanstalk|application|environment
          - aws|cloudformation|template|parameter
        OptionName: 
          - MaxSize
          - EC2KeyName
          - IamInstanceProfile
          - InstanceType
          - SecurityGroups
          - BreachDuration
          - LowerThreshold
          - MeasureName
          - Period
          - Unit
          - UpperThreshold
          - JVMOptions
          - AssociatePublicIpAddress
          - ELBSubnets
          - Subnets
          - VPCId
          - BatchSize
          - SSLCertificateId
          - ConnectionDrainingEnabled
          - Notification Endpoint
          - RootVolumeSize
          - RootVolumeType
          - RootVolumeIOPS
          - DesiredCapacity
          - MaxSize
          - MinSize
          - Recurrence
          - StartTime
          - Suspend
          - ELBScheme
          - BatchSizeType
          - CrossZone
          - AWSEBCloudWatchLogs8832c8d3f1a54c238a40e36f31ef55a0WebRequestLogGroup
          - EnvironmentVariables
