configuration:  
  projectName: Promotions
server:  
  port: 8080
properties:
  status: 1
---
spring:
  profiles: environments
Staging:
  STG-PromotionsService:
    status: 0
    serverType: Web
    properties:
      VersionLabel: STGPromotionsServiceVersion
      TemplateName: STGPromotionsServiceTemplate
      CNAMEPrefix: STG-PromotionsService
---
spring:
  profiles: versions
Staging:
  STGPromotionsServiceVersion:
    properties:
      Description: AWS ElasticBeanstalk Staging STG-PromotionsService Version
      SourceBundle: 
        S3Key: coreapp
---
spring:
  profiles: configurationTemplate
Staging:
  STGPromotionsServiceTemplate:
    properties:
      Description: AWS ElasticBeanstalk STG-PromotionsService Configuration Template
      SolutionStackName: 64bit Amazon Linux 2016.03 v2.2.0 running Tomcat 8 Java 8
      NumberOfOptionSettings: 34
      OptionSettings:
        Value:
        Namespace:
        OptionName: 
