configuration:  
  projectName: Solutions
server:  
  port: 8080
properties:
  status: 1
---
spring:
  profiles: environments
Staging:
  STG-Solutions:
    status: 0
    serverType: Web
    properties:
      VersionLabel: STGSolutionsVersion
      TemplateName: STGSolutionsTemplate
      CNAMEPrefix: STG-Solutions
---
spring:
  profiles: versions
Staging:
  STGSolutionsVersion:
    properties:
      Description: AWS ElasticBeanstalk Staging STGSolutions Version
      SourceBundle: 
        S3Key: coreapp
---
spring:
  profiles: configurationTemplate
Staging:
  STGSolutionsTemplate:
    properties:
      Description: AWS ElasticBeanstalk STG-Solutions Configuration Template
      SolutionStackName: 64bit Amazon Linux 2016.03 v2.2.0 running Tomcat 8 Java 8
      NumberOfOptionSettings: 34
      OptionSettings:
        Value:
        Namespace:
        OptionName: 
