configuration:  
  projectName: TripReport
server:  
  port: 8080
properties:
  status: 1
---
spring:
  profiles: environments
Staging:
  STG-TripReportWeb:
    status: 0
    serverType: Web
    properties:
      VersionLabel: STGTripReportWebVersion
      TemplateName: STGTripReportWebTemplate
      CNAMEPrefix: STG-TripReportWeb
  STG-TripReportWorker:
    status: 0
    serverType: Worker
    properties:
      VersionLabel: STGTripReportWorkerVersion
      TemplateName: STGTripReportWorkerTemplate
      CNAMEPrefix: STG-TripReportWorker
---
spring:
  profiles: versions
Staging:
  STGTripReportWebVersion:
    properties:
      Description: AWS ElasticBeanstalk Staging STG-TripReportWeb Version
      SourceBundle: 
        S3Key: coreapp
  STGTripReportWorkerVersion:
    properties:
      Description: AWS ElasticBeanstalk Staging STG-TripReportWorker Version
      SourceBundle: 
        S3Key: coreapp
---
spring:
  profiles: configurationTemplate
Staging:
  STGTripReportWebTemplate:
    properties:
      Description: AWS ElasticBeanstalk STG-TripReportWeb Configuration Template
      SolutionStackName: 64bit Amazon Linux 2016.03 v2.2.0 running Tomcat 8 Java 8
      NumberOfOptionSettings: 34
      OptionSettings:
        Value:
        Namespace:
        OptionName: 
  STGTripReportWorkerTemplate:
    properties:
      Description: AWS ElasticBeanstalk STG-TripReportWorker Configuration Template
      SolutionStackName: 64bit Amazon Linux 2016.03 v2.2.0 running Tomcat 8 Java 8
      NumberOfOptionSettings: 34
      OptionSettings:
        Value:
        Namespace:
        OptionName: 
