configuration:  
  projectName: Workers
server:  
  port: 8080
properties:
  status: 1
---
spring:
  profiles: environments
Staging:
  STG-RecentLocation:
    status: 0
    serverType: Web
    properties:
      VersionLabel: STGRecentLocationVersion
      TemplateName: STGRecentLocationTemplate
      CNAMEPrefix: STG-RecentLocation
  STG-PingService:
    status: 0
    serverType: Web
    properties:
      VersionLabel: STGPingServiceVersion
      TemplateName: STGPingServiceTemplate
      CNAMEPrefix: STG-PingService
  STG-PushyService:
    status: 0
    serverType: Web
    properties:
      VersionLabel: STGPushyServiceVersion
      TemplateName: STGPushyServiceTemplate
      CNAMEPrefix: STG-PushyService
---
spring:
  profiles: versions
Staging:
  STGRecentLocationVersion:
    properties:
      Description: AWS ElasticBeanstalk Staging STG-RecentLocation Version
      SourceBundle: 
        S3Key: coreapp
  STGPingServiceVersion:
    properties:
      Description: AWS ElasticBeanstalk Staging STG-PingService Version
      SourceBundle: 
        S3Key: coreapp
  STGPushyServiceVersion:
    properties:
      Description: AWS ElasticBeanstalk Staging STG-PushyService Version
      SourceBundle: 
        S3Key: coreapp
---
spring:
  profiles: configurationTemplate
Staging:
  STGRecentLocationTemplate:
    properties:
      Description: AWS ElasticBeanstalk STG-RecentLocation Configuration Template
      SolutionStackName: 64bit Amazon Linux 2016.03 v2.2.0 running Tomcat 8 Java 8
      NumberOfOptionSettings: 34
      OptionSettings:
        Value:
        Namespace:
        OptionName: 
  STGPingServiceTemplate:
    properties:
      Description: AWS ElasticBeanstalk STG-PingService Configuration Template
      SolutionStackName: 64bit Amazon Linux 2016.03 v2.2.0 running Tomcat 8 Java 8
      NumberOfOptionSettings: 34
      OptionSettings:
        Value:
        Namespace:
        OptionName: 
  STGPushyServiceTemplate:
    properties:
      Description: AWS ElasticBeanstalk STG-PushyService Configuration Template
      SolutionStackName: 64bit Amazon Linux 2016.03 v2.2.0 running Tomcat 8 Java 8
      NumberOfOptionSettings: 34
      OptionSettings:
        Value:
        Namespace:
        OptionName: 